---
# Source: testkube/charts/testkube-api/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: watchers-role-testkube
  labels:
    app.kubernetes.io/version: "1.14.6"
    helm.sh/chart: testkube-api-1.14.6
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: api-server
    app.kubernetes.io/instance: testkube
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - events
      - namespaces
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "apps"
    resources:
      - deployments
      - daemonsets
      - statefulsets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "networking.k8s.io"
      - "extensions"
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
---
# Source: testkube/charts/testkube-api/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: executors-role-testkube
  labels:
    app.kubernetes.io/version: "1.14.6"
    helm.sh/chart: testkube-api-1.14.6
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: api-server
    app.kubernetes.io/instance: testkube
rules:
  - apiGroups:
      - executor.testkube.io
    resources:
      - executors
    verbs:
      - get
      - watch
      - list
      - create
      - update
      - patch
      - delete
      - deletecollection
  - apiGroups:
      - executor.testkube.io
    resources:
      - executors/status
    verbs:
      - get
---
# Source: testkube/charts/testkube-api/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jobs-role-testkube
  labels:
    app.kubernetes.io/version: "1.14.6"
    helm.sh/chart: testkube-api-1.14.6
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: api-server
    app.kubernetes.io/instance: testkube
rules:
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - watch
      - list
      - create
      - delete
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
    verbs:
      - get
      - watch
      - list
      - create
---
# Source: testkube/charts/testkube-api/templates/role.yaml
# permissions for end users to edit tests.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: script-role-testkube
  labels:
    app.kubernetes.io/version: "1.14.6"
    helm.sh/chart: testkube-api-1.14.6
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: api-server
    app.kubernetes.io/instance: testkube
rules:
  - apiGroups:
      - tests.testkube.io
    resources:
      - scripts
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
      - deletecollection
  - apiGroups:
      - tests.testkube.io
    resources:
      - scripts/status
    verbs:
      - get
---
# Source: testkube/charts/testkube-api/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: test-role-testkube
  labels:
    app.kubernetes.io/version: "1.14.6"
    helm.sh/chart: testkube-api-1.14.6
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: api-server
    app.kubernetes.io/instance: testkube
rules:
  - apiGroups:
      - tests.testkube.io
    resources:
      - tests
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
      - deletecollection
  - apiGroups:
      - tests.testkube.io
    resources:
      - tests/status
    verbs:
      - get
      - patch
      - update
---
# Source: testkube/charts/testkube-api/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secrets-role-testkube
  labels:
    app.kubernetes.io/version: "1.14.6"
    helm.sh/chart: testkube-api-1.14.6
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: api-server
    app.kubernetes.io/instance: testkube
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
      - deletecollection
---
# Source: testkube/charts/testkube-api/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: testsuite-role-testkube
  labels:
    app.kubernetes.io/version: "1.14.6"
    helm.sh/chart: testkube-api-1.14.6
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: api-server
    app.kubernetes.io/instance: testkube
rules:
  - apiGroups:
      - tests.testkube.io
    resources:
      - testsuites
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
      - deletecollection
  - apiGroups:
      - tests.testkube.io
    resources:
      - testsuites/status
    verbs:
      - get
      - patch
      - update
---
# Source: testkube/charts/testkube-api/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: webhook-role-testkube
  labels:
    app.kubernetes.io/version: "1.14.6"
    helm.sh/chart: testkube-api-1.14.6
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: api-server
    app.kubernetes.io/instance: testkube
rules:
  - apiGroups:
      - executor.testkube.io
    resources:
      - webhooks
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
      - deletecollection
  - apiGroups:
      - executor.testkube.io
    resources:
      - webhooks/status
    verbs:
      - get
---
# Source: testkube/charts/testkube-api/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: configmaps-role-testkube
  labels:
    app.kubernetes.io/version: "1.14.6"
    helm.sh/chart: testkube-api-1.14.6
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: api-server
    app.kubernetes.io/instance: testkube
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - get
      - patch
      - update
---
# Source: testkube/charts/testkube-api/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: testsource-role-testkube
  labels:
    app.kubernetes.io/version: "1.14.6"
    helm.sh/chart: testkube-api-1.14.6
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: api-server
    app.kubernetes.io/instance: testkube
rules:
  - apiGroups:
      - tests.testkube.io
    resources:
      - testsources
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
      - deletecollection
  - apiGroups:
      - tests.testkube.io
    resources:
      - testsources/status
    verbs:
      - get
---
# Source: testkube/charts/testkube-api/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: testtriggers-role-testkube
  labels:
    app.kubernetes.io/version: "1.14.6"
    helm.sh/chart: testkube-api-1.14.6
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: api-server
    app.kubernetes.io/instance: testkube
rules:
  - apiGroups:
      - tests.testkube.io
    resources:
      - testtriggers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
      - deletecollection
  - apiGroups:
      - tests.testkube.io
    resources:
      - testtriggers/status
    verbs:
      - get
---
# Source: testkube/charts/testkube-api/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: persistentvolumeclaims-role-testkube
  labels:
    app.kubernetes.io/version: "1.14.6"
    helm.sh/chart: testkube-api-1.14.6
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: api-server
    app.kubernetes.io/instance: testkube
rules:
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - create
      - get
      - delete
---
# Source: testkube/charts/testkube-api/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: testexecution-role-testkube
  labels:
    app.kubernetes.io/version: "1.14.6"
    helm.sh/chart: testkube-api-1.14.6
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: api-server
    app.kubernetes.io/instance: testkube
rules:
  - apiGroups:
      - tests.testkube.io
    resources:
      - testexecutions
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
      - deletecollection
  - apiGroups:
      - tests.testkube.io
    resources:
      - testexecutions/status
    verbs:
      - get
      - patch
      - update
---
# Source: testkube/charts/testkube-api/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: testsuiteexecution-role-testkube
  labels:
    app.kubernetes.io/version: "1.14.6"
    helm.sh/chart: testkube-api-1.14.6
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: api-server
    app.kubernetes.io/instance: testkube
rules:
  - apiGroups:
      - tests.testkube.io
    resources:
      - testsuiteexecutions
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
      - deletecollection
  - apiGroups:
      - tests.testkube.io
    resources:
      - testsuiteexecutions/status
    verbs:
      - get
      - patch
      - update
---
# Source: testkube/charts/testkube-api/templates/role.yaml
---
