---
# Source: testkube/charts/testkube-operator/templates/pre-upgrade-sa.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: testkube-operator-pre-upgrade-sa
  namespace: default
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
---
# Source: testkube/charts/testkube-operator/templates/pre-upgrade-sa.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: testkube-operator-pre-upgrade-role
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["create","delete","get","list","patch","update","watch"]
---
# Source: testkube/charts/testkube-operator/templates/pre-upgrade-sa.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: testkube-operator-pre-upgrade-rolebinding
  namespace: default
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: testkube-operator-pre-upgrade-role
subjects:
  - kind: ServiceAccount
    name: testkube-operator-pre-upgrade-sa
    namespace: default
