---
# Source: testkube/charts/testkube-operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: testkube-operator-controller-manager
  namespace: default
  labels:
    app.kubernetes.io/version: "1.14.0"
    helm.sh/chart: testkube-operator-1.14.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: testkube-operator
    app.kubernetes.io/instance: testkube
---
# Source: testkube/charts/testkube-operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: testkube-operator-webhook-cert-mgr
  namespace: default
  labels:
    app.kubernetes.io/version: "1.14.0"
    helm.sh/chart: testkube-operator-1.14.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: testkube-operator
    app.kubernetes.io/instance: testkube
    app.kubernetes.io/component: admission-webhook
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
